variable "subscription_id" {
  type    = string
  default = ""
}

variable "tenant_id" {
  type    = string
  default = ""
}

variable "client_id" {
  type    = string
  default = ""
}

variable "client_secret" {
  sensitive = true
  type      = string
  default   = ""
}

variable "dynatrace_install_url" {
  default = "https://dtcdn.net/one-agent-install.sh"
}
variable "dynatrace_install_params" {
  default = "--set-install-only=true --set-infra-only=false"
}


source "azure-arm" "autogenerated_1" {
  subscription_id = var.subscription_id
  tenant_id       = var.tenant_id
  client_id       = var.client_id
  client_secret   = var.client_secret
  image_offer     = "RHEL"
  image_publisher = "RedHat"
  image_sku       = "8-lvm-gen2"
  #location                         = "East US 2"
  managed_image_name                = "rhel-golden-nprd-eus2-001"
  managed_image_resource_group_name = "rg-core-tools-nprd-eus2"
  os_type                           = "Linux"
  vm_size                           = "Standard_DS2_v2"
  os_disk_size_gb                   =  64
  build_resource_group_name         = "rg-core-tools-nprd-eus2"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "shell" {
    execute_command = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"
    inline          = ["yum -y update", "yum install -y nginx"]
    inline_shebang  = "/bin/sh -x"
  }

  provisioner "shell" {
    execute_command = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"
    inline = [
        "curl -sSL https://kwi83437.apps.dynatrace.com/ui/apps/dynatrace.classic.deploy.oneagent/rest/deployment/installer/agent/unix/default/latest?arch=x86 -o /opt/one-agent-install.sh",
        "chmod +x /opt/one-agent-install.sh"
      ]
  }

  provisioner "shell" {
    execute_command = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"
    script          = "packer/scripts/ubuntu/prep.sh"
  }

}